/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Content;

import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author NobbyDobbyCobby
 */
public class motorph_generatepayslip extends javax.swing.JPanel {

    /**
     * Creates new form motorph_generatepayslip
     */
    public motorph_generatepayslip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PayslipGenerator = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtgenpayslip_empno = new javax.swing.JTextField();
        txtgenpayslip_startdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtgenpayslip_enddate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btngeneratepayslip = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 800));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        PayslipGenerator.setBackground(new java.awt.Color(255, 255, 255));
        PayslipGenerator.setMaximumSize(new java.awt.Dimension(1000, 800));
        PayslipGenerator.setMinimumSize(new java.awt.Dimension(1000, 800));
        PayslipGenerator.setPreferredSize(new java.awt.Dimension(1000, 800));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Payslip Generator");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Employee No.:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Pay Coverage:");

        txtgenpayslip_empno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtgenpayslip_startdate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("MM/DD/YYYY");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("to");

        txtgenpayslip_enddate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtgenpayslip_enddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenpayslip_enddateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setText("MM/DD/YYYY");

        btngeneratepayslip.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btngeneratepayslip.setText("Generate Payslip");
        btngeneratepayslip.setToolTipText("");
        btngeneratepayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeneratepayslipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PayslipGeneratorLayout = new javax.swing.GroupLayout(PayslipGenerator);
        PayslipGenerator.setLayout(PayslipGeneratorLayout);
        PayslipGeneratorLayout.setHorizontalGroup(
            PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayslipGeneratorLayout.createSequentialGroup()
                        .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                                .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                                        .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                                        .addComponent(txtgenpayslip_startdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtgenpayslip_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                        .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btngeneratepayslip)
                            .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtgenpayslip_empno, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(561, 561, 561))
        );
        PayslipGeneratorLayout.setVerticalGroup(
            PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtgenpayslip_empno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgenpayslip_startdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtgenpayslip_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btngeneratepayslip)
                .addContainerGap(515, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PayslipGenerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PayslipGenerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtgenpayslip_enddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenpayslip_enddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenpayslip_enddateActionPerformed

    private void btngeneratepayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeneratepayslipActionPerformed
        // TODO add your handling code here:

        String empNumber = txtgenpayslip_empno.getText().trim();
        String payRangeStart = txtgenpayslip_startdate.getText().trim();
        String payRangeEnd = txtgenpayslip_enddate.getText().trim();

        try {

            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            sdf.setLenient(false);
            Date startDate = sdf.parse(payRangeStart);
            Date endDate = sdf.parse(payRangeEnd);
            System.out.print(startDate);
            System.out.print(endDate);

            // Show success message
            JOptionPane.showMessageDialog(this,
                "Payslip generated for employee #" + empNumber +
                "\nCoverage: " + sdf.format(startDate) + " - " + sdf.format(endDate),
                "Success", JOptionPane.INFORMATION_MESSAGE
            );

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException | ParseException ex) {
            JOptionPane.showMessageDialog(this, "Unexpected error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btngeneratepayslipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PayslipGenerator;
    private javax.swing.JButton btngeneratepayslip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtgenpayslip_empno;
    private javax.swing.JTextField txtgenpayslip_enddate;
    private javax.swing.JTextField txtgenpayslip_startdate;
    // End of variables declaration//GEN-END:variables
}
