/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorph_app;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author abigail
 */
public class motorph_generatepayslip extends javax.swing.JFrame {

    /**
     * Creates new form motorph_generatepayslip
     */
    public motorph_generatepayslip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftMenu = new javax.swing.JPanel();
        btnempdashboard = new javax.swing.JButton();
        btnleaveapp = new javax.swing.JButton();
        btngenpayslip = new javax.swing.JButton();
        btnhelpdesk = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        RightDashboard = new javax.swing.JPanel();
        PayslipGenerator = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtgenpayslip_empno = new javax.swing.JTextField();
        txtgenpayslip_startdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtgenpayslip_enddate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btngeneratepayslip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 900));
        setMinimumSize(new java.awt.Dimension(1200, 900));

        LeftMenu.setBackground(new java.awt.Color(153, 0, 0));
        LeftMenu.setMaximumSize(new java.awt.Dimension(200, 500));
        LeftMenu.setMinimumSize(new java.awt.Dimension(200, 500));
        LeftMenu.setSize(new java.awt.Dimension(200, 500));
        LeftMenu.setLayout(null);

        btnempdashboard.setText("Employee Dashboard");
        btnempdashboard.setMaximumSize(new java.awt.Dimension(180, 30));
        btnempdashboard.setMinimumSize(new java.awt.Dimension(180, 30));
        btnempdashboard.setPreferredSize(new java.awt.Dimension(180, 30));
        btnempdashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempdashboardActionPerformed(evt);
            }
        });
        LeftMenu.add(btnempdashboard);
        btnempdashboard.setBounds(6, 135, 188, 30);

        btnleaveapp.setText("Leave Application");
        btnleaveapp.setMaximumSize(new java.awt.Dimension(180, 30));
        btnleaveapp.setMinimumSize(new java.awt.Dimension(180, 30));
        btnleaveapp.setPreferredSize(new java.awt.Dimension(180, 30));
        btnleaveapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleaveappActionPerformed(evt);
            }
        });
        LeftMenu.add(btnleaveapp);
        btnleaveapp.setBounds(6, 183, 188, 30);

        btngenpayslip.setText("Generate Payslip");
        btngenpayslip.setMaximumSize(new java.awt.Dimension(180, 30));
        btngenpayslip.setMinimumSize(new java.awt.Dimension(180, 30));
        btngenpayslip.setPreferredSize(new java.awt.Dimension(180, 30));
        btngenpayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenpayslipActionPerformed(evt);
            }
        });
        LeftMenu.add(btngenpayslip);
        btngenpayslip.setBounds(6, 231, 188, 30);

        btnhelpdesk.setText("Help Desk");
        btnhelpdesk.setMaximumSize(new java.awt.Dimension(180, 30));
        btnhelpdesk.setMinimumSize(new java.awt.Dimension(180, 30));
        btnhelpdesk.setPreferredSize(new java.awt.Dimension(180, 30));
        btnhelpdesk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhelpdeskActionPerformed(evt);
            }
        });
        LeftMenu.add(btnhelpdesk);
        btnhelpdesk.setBounds(6, 279, 188, 30);

        btnlogout.setText("Log out");
        btnlogout.setMaximumSize(new java.awt.Dimension(180, 30));
        btnlogout.setMinimumSize(new java.awt.Dimension(180, 30));
        btnlogout.setPreferredSize(new java.awt.Dimension(180, 30));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        LeftMenu.add(btnlogout);
        btnlogout.setBounds(10, 400, 180, 30);
        LeftMenu.add(jSeparator1);
        jSeparator1.setBounds(6, 107, 188, 10);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome to MotorPH");
        LeftMenu.add(jLabel2);
        jLabel2.setBounds(28, 45, 145, 18);

        RightDashboard.setBackground(new java.awt.Color(255, 255, 255));
        RightDashboard.setLocation(new java.awt.Point(200, 200));
        RightDashboard.setMaximumSize(new java.awt.Dimension(1000, 800));
        RightDashboard.setMinimumSize(new java.awt.Dimension(1000, 800));

        PayslipGenerator.setBackground(new java.awt.Color(255, 255, 255));
        PayslipGenerator.setMixingCutoutShape(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Payslip Generator");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Employee No.:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Pay Coverage:");

        txtgenpayslip_empno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtgenpayslip_startdate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("MM/DD/YYYY");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("to");

        txtgenpayslip_enddate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtgenpayslip_enddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenpayslip_enddateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setText("MM/DD/YYYY");

        btngeneratepayslip.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btngeneratepayslip.setText("Generate Payslip");
        btngeneratepayslip.setToolTipText("");
        btngeneratepayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeneratepayslipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PayslipGeneratorLayout = new javax.swing.GroupLayout(PayslipGenerator);
        PayslipGenerator.setLayout(PayslipGeneratorLayout);
        PayslipGeneratorLayout.setHorizontalGroup(
            PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayslipGeneratorLayout.createSequentialGroup()
                        .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                                .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                                .addComponent(txtgenpayslip_startdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtgenpayslip_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                        .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btngeneratepayslip)
                            .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtgenpayslip_empno, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(561, 561, 561))
        );
        PayslipGeneratorLayout.setVerticalGroup(
            PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayslipGeneratorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtgenpayslip_empno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PayslipGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgenpayslip_startdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtgenpayslip_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btngeneratepayslip)
                .addContainerGap(603, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RightDashboardLayout = new javax.swing.GroupLayout(RightDashboard);
        RightDashboard.setLayout(RightDashboardLayout);
        RightDashboardLayout.setHorizontalGroup(
            RightDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightDashboardLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PayslipGenerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RightDashboardLayout.setVerticalGroup(
            RightDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightDashboardLayout.createSequentialGroup()
                .addComponent(PayslipGenerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LeftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(RightDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RightDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LeftMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnempdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempdashboardActionPerformed
        // TODO add your handling code here:
        motorph_dashboard MainDashboard = new motorph_dashboard();
            MainDashboard.setLocationRelativeTo(null);
            MainDashboard.setVisible(true);
            this.dispose();

    }//GEN-LAST:event_btnempdashboardActionPerformed

    private void btnleaveappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleaveappActionPerformed
        // TODO add your handling code here:
        motorph_leaveapplication LeaveApplication = new motorph_leaveapplication();
        LeaveApplication.setLocationRelativeTo(null);
        LeaveApplication.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnleaveappActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:

        motorph_login LoginFrame = new motorph_login();
        LoginFrame.setLocationRelativeTo(null);
        LoginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void txtgenpayslip_enddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenpayslip_enddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenpayslip_enddateActionPerformed

    
    
    
    private void btngeneratepayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeneratepayslipActionPerformed
        // TODO add your handling code here:
        
    String empNumber = txtgenpayslip_empno.getText().trim();
    String payRangeStart = txtgenpayslip_startdate.getText().trim();
    String payRangeEnd = txtgenpayslip_enddate.getText().trim();
    
try {

    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
    sdf.setLenient(false);
    Date startDate = sdf.parse(payRangeStart);
    Date endDate = sdf.parse(payRangeEnd);
System.out.print(startDate);
System.out.print(endDate);

            // Show success message
            JOptionPane.showMessageDialog(this,
                "Payslip generated for employee #" + empNumber +
                "\nCoverage: " + sdf.format(startDate) + " - " + sdf.format(endDate),
                "Success", JOptionPane.INFORMATION_MESSAGE
            );

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unexpected error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btngeneratepayslipActionPerformed

    private void btngenpayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenpayslipActionPerformed
        // TODO add your handling code here:
        motorph_generatepayslip GenPayslip = new motorph_generatepayslip();
        GenPayslip.setLocationRelativeTo(null);
        GenPayslip.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btngenpayslipActionPerformed

    private void btnhelpdeskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhelpdeskActionPerformed
        // TODO add your handling code here:
        motorph_helpdesk HelpDesk = new motorph_helpdesk();
        HelpDesk.setLocationRelativeTo(null);
        HelpDesk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhelpdeskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(motorph_generatepayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(motorph_generatepayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(motorph_generatepayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(motorph_generatepayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new motorph_generatepayslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftMenu;
    private javax.swing.JPanel PayslipGenerator;
    private javax.swing.JPanel RightDashboard;
    private javax.swing.JButton btnempdashboard;
    private javax.swing.JButton btngeneratepayslip;
    private javax.swing.JButton btngenpayslip;
    private javax.swing.JButton btnhelpdesk;
    private javax.swing.JButton btnleaveapp;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtgenpayslip_empno;
    private javax.swing.JTextField txtgenpayslip_enddate;
    private javax.swing.JTextField txtgenpayslip_startdate;
    // End of variables declaration//GEN-END:variables
}
