/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorph_app;

/**
 *
 * @author abigail
 */
public class motorph_helpdesk extends javax.swing.JFrame {

    /**
     * Creates new form motorph_helpdesk
     */
    public motorph_helpdesk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftMenu = new javax.swing.JPanel();
        btnempdashboard = new javax.swing.JButton();
        btnleaveapp = new javax.swing.JButton();
        btngenpayslip = new javax.swing.JButton();
        btnhelpdesk = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        RightDashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 900));
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setResizable(false);

        LeftMenu.setBackground(new java.awt.Color(153, 0, 0));
        LeftMenu.setMaximumSize(new java.awt.Dimension(200, 500));
        LeftMenu.setMinimumSize(new java.awt.Dimension(200, 500));
        LeftMenu.setSize(new java.awt.Dimension(200, 500));
        LeftMenu.setLayout(null);

        btnempdashboard.setText("Employee Dashboard");
        btnempdashboard.setMaximumSize(new java.awt.Dimension(180, 30));
        btnempdashboard.setMinimumSize(new java.awt.Dimension(180, 30));
        btnempdashboard.setPreferredSize(new java.awt.Dimension(180, 30));
        btnempdashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempdashboardActionPerformed(evt);
            }
        });
        LeftMenu.add(btnempdashboard);
        btnempdashboard.setBounds(6, 135, 188, 30);

        btnleaveapp.setText("Leave Application");
        btnleaveapp.setMaximumSize(new java.awt.Dimension(180, 30));
        btnleaveapp.setMinimumSize(new java.awt.Dimension(180, 30));
        btnleaveapp.setPreferredSize(new java.awt.Dimension(180, 30));
        btnleaveapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleaveappActionPerformed(evt);
            }
        });
        LeftMenu.add(btnleaveapp);
        btnleaveapp.setBounds(6, 183, 188, 30);

        btngenpayslip.setText("Generate Payslip");
        btngenpayslip.setMaximumSize(new java.awt.Dimension(180, 30));
        btngenpayslip.setMinimumSize(new java.awt.Dimension(180, 30));
        btngenpayslip.setPreferredSize(new java.awt.Dimension(180, 30));
        btngenpayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenpayslipActionPerformed(evt);
            }
        });
        LeftMenu.add(btngenpayslip);
        btngenpayslip.setBounds(6, 231, 188, 30);

        btnhelpdesk.setText("Help Desk");
        btnhelpdesk.setMaximumSize(new java.awt.Dimension(180, 30));
        btnhelpdesk.setMinimumSize(new java.awt.Dimension(180, 30));
        btnhelpdesk.setPreferredSize(new java.awt.Dimension(180, 30));
        btnhelpdesk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhelpdeskActionPerformed(evt);
            }
        });
        LeftMenu.add(btnhelpdesk);
        btnhelpdesk.setBounds(6, 279, 188, 30);

        btnlogout.setText("Log out");
        btnlogout.setMaximumSize(new java.awt.Dimension(180, 30));
        btnlogout.setMinimumSize(new java.awt.Dimension(180, 30));
        btnlogout.setPreferredSize(new java.awt.Dimension(180, 30));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        LeftMenu.add(btnlogout);
        btnlogout.setBounds(10, 400, 180, 30);
        LeftMenu.add(jSeparator1);
        jSeparator1.setBounds(6, 107, 188, 10);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome to MotorPH");
        LeftMenu.add(jLabel2);
        jLabel2.setBounds(28, 45, 145, 18);

        RightDashboard.setBackground(new java.awt.Color(255, 255, 255));
        RightDashboard.setMaximumSize(new java.awt.Dimension(1000, 800));
        RightDashboard.setMinimumSize(new java.awt.Dimension(1000, 800));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Help Desk");

        javax.swing.GroupLayout RightDashboardLayout = new javax.swing.GroupLayout(RightDashboard);
        RightDashboard.setLayout(RightDashboardLayout);
        RightDashboardLayout.setHorizontalGroup(
            RightDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightDashboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(883, Short.MAX_VALUE))
        );
        RightDashboardLayout.setVerticalGroup(
            RightDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(864, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LeftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(RightDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RightDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnempdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempdashboardActionPerformed
        // TODO add your handling code here:
        motorph_dashboard MainDashboard = new motorph_dashboard();
        MainDashboard.setLocationRelativeTo(null);
        MainDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnempdashboardActionPerformed

    private void btnleaveappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleaveappActionPerformed
        // TODO add your handling code here:
        motorph_leaveapplication LeaveApplication = new motorph_leaveapplication();
        LeaveApplication.setLocationRelativeTo(null);
        LeaveApplication.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnleaveappActionPerformed

    private void btngenpayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenpayslipActionPerformed
        // TODO add your handling code here:
        motorph_generatepayslip GenPayslip = new motorph_generatepayslip();
        GenPayslip.setLocationRelativeTo(null);
        GenPayslip.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btngenpayslipActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:

        motorph_login LoginFrame = new motorph_login();
        LoginFrame.setLocationRelativeTo(null);
        LoginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnhelpdeskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhelpdeskActionPerformed
        // TODO add your handling code here:
        motorph_helpdesk HelpDesk = new motorph_helpdesk();
        HelpDesk.setLocationRelativeTo(null);
        HelpDesk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhelpdeskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(motorph_helpdesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(motorph_helpdesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(motorph_helpdesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(motorph_helpdesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new motorph_helpdesk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftMenu;
    private javax.swing.JPanel RightDashboard;
    private javax.swing.JButton btnempdashboard;
    private javax.swing.JButton btngenpayslip;
    private javax.swing.JButton btnhelpdesk;
    private javax.swing.JButton btnleaveapp;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
